/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * event.java
 *
 * Created on Aug 1, 2017, 3:32:13 PM
 */

package collegeclub;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HP
 */
public class event extends javax.swing.JFrame {
    ConnectionClass cobj;
    PreparedStatement pst;
    ResultSet rst;
    long clbid[];
long eid;
DefaultTableModel model;
JTable table;
JScrollPane js;
    /** Creates new form event */
    public event() {
        initComponents();


        cobj = new ConnectionClass();
        model = new DefaultTableModel();
    table = new JTable(model);
js = new JScrollPane(table);
model.addColumn("Club ID");
model.addColumn("Event");
model.addColumn(" Name");
model.addColumn("Type");
model.addColumn("Proposal Date");
model.addColumn("Closing Date");
model.addColumn("Event Date");
model.addColumn("Venue");
model.addColumn("Participation fee");
model.addColumn("Time");
model.addColumn("Chief Guest");
model.addColumn("Prize1");
model.addColumn("Prize2");
model.addColumn("Prize3");

js.setBounds(700,50,500,400);
add(js);
        cobj.Connect();
        clbid = new long[100];
        int index=0;
        try
        {
            pst=cobj.con.prepareStatement("select * from tbEvent");
rst=pst.executeQuery();
while(rst.next())
{
model.insertRow(model.getRowCount(), new Object[] { rst.getString(1),rst.getString(2),rst.getString(3),rst.getString(4),rst.getString(5),rst.getString(6),rst.getString(7),rst.getString(8),rst.getString(9),rst.getString(10),rst.getString(11),rst.getString(12),rst.getString(13),rst.getString(14)});
}

        pst= cobj.con.prepareStatement("select clubid, clubname from tbclub");
        rst = pst.executeQuery();
               while (rst.next())
               {
               clbid[index]=rst.getLong(1);
               index++;
             jComboBox1.addItem(rst.getString(2));
               }
        rst.close();

        }
        catch(Exception ex)
        {
        System.out.print("error in populating clubid"+ex);
        }
        cobj.DisConnect();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel10 = new javax.swing.JLabel();
        resetjbutton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        proposaljTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        timejTextField8 = new javax.swing.JTextField();
        chiefjTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        closingjTextField4 = new javax.swing.JTextField();
        p2jTextField11 = new javax.swing.JTextField();
        namejTextField13 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        searchjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        namejLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        p1jTextField1o = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        updatejButton = new javax.swing.JButton();
        edatejTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        feejTextField7 = new javax.swing.JTextField();
        venuejTextField6 = new javax.swing.JTextField();
        savejButton = new javax.swing.JButton();
        p3jTextField12 = new javax.swing.JTextField();

        jLabel13.setText("jLabel13");

        jTextField10.setText("jTextField10");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setTitle("Event");
        jInternalFrame1.setVisible(true);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Office-Customer-Male-Light-icon.png"))); // NOI18N
        jLabel10.setText("Chief guest");

        resetjbutton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        resetjbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/reset.png"))); // NOI18N
        resetjbutton.setText("Reset");
        resetjbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetjbuttonActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Calendar-icon (1).png"))); // NOI18N
        jLabel5.setText("Closing date");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Calendar-icon (1).png"))); // NOI18N
        jLabel4.setText("Proposal date");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Badge-Prize-icon.png"))); // NOI18N
        jLabel11.setText("Prize1");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Time-And-Date-Timer-icon.png"))); // NOI18N
        jLabel9.setText("Time");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Badge-Prize-icon.png"))); // NOI18N
        jLabel12.setText("Prize2");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Question-type-drag-drop-icon.png"))); // NOI18N
        jLabel3.setText("Type");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Calendar-icon.png"))); // NOI18N
        jLabel6.setText("Event date");

        searchjButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Search-icon.png"))); // NOI18N
        searchjButton.setText("Search");
        searchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Cursor-icon (1).png"))); // NOI18N
        jLabel2.setText("Select Club");

        namejLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Username.png"))); // NOI18N
        namejLabel15.setText("Name");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Badge-Prize-icon.png"))); // NOI18N
        jLabel14.setText("Prize3");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/money-icon.png"))); // NOI18N
        jLabel8.setText("Participation fee");

        updatejButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updatejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/update.png"))); // NOI18N
        updatejButton.setText("Update");
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Places-repository-icon.png"))); // NOI18N
        jLabel7.setText("Venue");

        savejButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        savejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Apps-File-Save-B-icon.png"))); // NOI18N
        savejButton.setText("Save");
        savejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jInternalFrame1Layout = new org.jdesktop.layout.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jInternalFrame1Layout.createSequentialGroup()
                        .add(jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(jInternalFrame1Layout.createSequentialGroup()
                        .add(jLabel14)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(jInternalFrame1Layout.createSequentialGroup()
                        .add(jLabel12)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(jInternalFrame1Layout.createSequentialGroup()
                        .add(jLabel11)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(jInternalFrame1Layout.createSequentialGroup()
                        .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                .add(jLabel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabel10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(jInternalFrame1Layout.createSequentialGroup()
                                .add(savejButton)
                                .add(23, 23, 23)
                                .add(searchjButton)))
                        .add(13, 13, 13))
                    .add(jInternalFrame1Layout.createSequentialGroup()
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(jInternalFrame1Layout.createSequentialGroup()
                        .add(namejLabel15)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(jInternalFrame1Layout.createSequentialGroup()
                        .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .add(165, 165, 165))
                    .add(jInternalFrame1Layout.createSequentialGroup()
                        .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jInternalFrame1Layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(updatejButton)
                        .add(18, 18, 18)
                        .add(resetjbutton))
                    .add(jInternalFrame1Layout.createSequentialGroup()
                        .add(32, 32, 32)
                        .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, namejTextField13)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jComboBox1, 0, 154, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jTextField2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, closingjTextField4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, proposaljTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, edatejTextField5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .add(venuejTextField6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, feejTextField7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, timejTextField8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, chiefjTextField9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, p1jTextField1o, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, p2jTextField11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, p3jTextField12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(namejLabel15)
                    .add(namejTextField13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(proposaljTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(13, 13, 13)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(closingjTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel6)
                    .add(edatejTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(venuejTextField6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(feejTextField7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(timejTextField8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(chiefjTextField9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(p1jTextField1o, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(p2jTextField11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel14)
                    .add(p3jTextField12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(savejButton)
                    .add(updatejButton)
                    .add(resetjbutton)
                    .add(searchjButton))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jInternalFrame1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(775, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jInternalFrame1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                .add(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButtonActionPerformed
    if(namejTextField13.getText().equals(""))
        {
            System.out.println("Enter name");
        }
 else{

        cobj.Connect();
     try{
          pst=cobj.con.prepareStatement("{call prcInsertEvent(?,?,?,?,?,?,?,?,?,?,?,?,?)} ");
                        pst.setLong(1,clbid[jComboBox1.getSelectedIndex()]);
                        pst.setString(2,namejTextField13.getText());
                        pst.setString(3,jTextField2.getText());
                        pst.setString(4,proposaljTextField.getText());
                        pst.setString(5,closingjTextField4.getText());
                        pst.setString(6,edatejTextField5.getText());
                        pst.setString(7,venuejTextField6.getText());
                        pst.setString(8,feejTextField7.getText());
                        pst.setString(9,timejTextField8.getText());
                        pst.setString(10,chiefjTextField9.getText());
                        pst.setString(11,p1jTextField1o.getText());
                        pst.setString(12,p2jTextField11.getText());
                        pst.setString(13,p3jTextField12.getText());

                      if(pst.execute()==false)
                      {
                          if(pst.getUpdateCount()>0)
                          {
                              System.out.print("Record saved");
                              jComboBox1.setSelectedIndex(0);
                              namejTextField13.setText("");
                             jTextField2.setText("");
                              proposaljTextField.setText("");
                              closingjTextField4.setText("");
                              edatejTextField5.setText("");
                              venuejTextField6.setText("");
                            feejTextField7.setText("");
                            timejTextField8.setText("");
                             chiefjTextField9.setText("");
                            p1jTextField1o.setText("");
                            p2jTextField11.setText("");
                            p3jTextField12.setText("");

     }
 else{
                              System.out.print("Record exists");
 }
     }
        }
     catch(Exception ex)
     {
         System.out.println("Error in insert"+ex);
     }
        cobj.DisConnect();
        }
    }//GEN-LAST:event_savejButtonActionPerformed

    private void searchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjButtonActionPerformed
        // TODO add your handling code here:
        if(namejTextField13.getText().equals(""))
        {
            System.out.print("Enter name");
        }

        cobj.Connect();
            try

            {
                pst=cobj.con.prepareStatement("Select * from tbevent where name=?");
                pst.setString(1,namejTextField13.getText());
                rst=pst.executeQuery();
                if(rst.next())
                {
                    eid=rst.getLong(1);
                    jComboBox1.setSelectedIndex(new searcharray().find(clbid,rst.getLong(2)));
                    namejTextField13.setText(rst.getString(3).trim());
                    jTextField2.setText(rst.getString(4).trim());
                    proposaljTextField.setText(rst.getString(5).trim());
                    closingjTextField4.setText(rst.getString(6).trim());
                    edatejTextField5.setText(rst.getString(7).trim());
                    venuejTextField6.setText(rst.getString(8).trim());
                    feejTextField7.setText(rst.getString(9).trim());
                    timejTextField8.setText(rst.getString(10).trim());
                   chiefjTextField9.setText(rst.getString(11).trim());
p1jTextField1o.setText(rst.getString(12).trim());
  p2jTextField11.setText(rst.getString(13).trim());
   p3jTextField12.setText(rst.getString(14).trim());
                }

 else
                {
                    System.out.println("record not found");
                }
 }



 catch(Exception ex)
            {
     System.out.println("error in search"+ex);
        }
    }//GEN-LAST:event_searchjButtonActionPerformed

    private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed
       cobj.Connect();
try
{
    pst=cobj.con.prepareCall("{call prcupdatevent(?,?,?,?,?,?,?,?,?,?,?,?,?,?)}");
pst.setLong(1,eid);
pst.setLong(2,clbid[jComboBox1.getSelectedIndex()]);
pst.setString(3,namejTextField13.getText());
pst.setString(4,jTextField2.getText());
pst.setString(5,proposaljTextField.getText());
pst.setString(6,closingjTextField4.getText());
pst.setString(7,edatejTextField5.getText());
pst.setString(8,venuejTextField6.getText());
pst.setString(9,feejTextField7.getText());
pst.setString(10,timejTextField8.getText());
pst.setString(11,chiefjTextField9.getText());
pst.setString(12,p1jTextField1o.getText());
pst.setString(13,p2jTextField11.getText());
pst.setString(14,p3jTextField12.getText());
if(pst.execute()==false)
{
    if(pst.getUpdateCount()>0)
    {
        System.out.println("Record Updated");
        jComboBox1.setSelectedIndex(0);
        namejTextField13.setText("");
        jTextField2.setText("");
        proposaljTextField.setText("");
       closingjTextField4.setText("");
        edatejTextField5.setText("");
        venuejTextField6.setText("");
        feejTextField7.setText("");
        timejTextField8.setText("");
        chiefjTextField9.setText("");
     p1jTextField1o.setText("");
        p2jTextField11.setText("");
        p3jTextField12.setText("");
    }
 else{
        System.out.println("Record not updated");
 }
}
        }
catch(Exception ex)
{
    System.out.println("Error in Update"+ex);
}
cobj.DisConnect();

    }//GEN-LAST:event_updatejButtonActionPerformed

    private void resetjbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetjbuttonActionPerformed
        namejTextField13.setText("");
        jTextField2.setText("");
        proposaljTextField.setText("");
       closingjTextField4.setText("");
        edatejTextField5.setText("");
        venuejTextField6.setText("");
        feejTextField7.setText("");
        timejTextField8.setText("");
        chiefjTextField9.setText("");
     p1jTextField1o.setText("");
        p2jTextField11.setText("");
        p3jTextField12.setText("");
    }//GEN-LAST:event_resetjbuttonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new event().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chiefjTextField9;
    private javax.swing.JTextField closingjTextField4;
    private javax.swing.JTextField edatejTextField5;
    private javax.swing.JTextField feejTextField7;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel namejLabel15;
    private javax.swing.JTextField namejTextField13;
    private javax.swing.JTextField p1jTextField1o;
    private javax.swing.JTextField p2jTextField11;
    private javax.swing.JTextField p3jTextField12;
    private javax.swing.JTextField proposaljTextField;
    private javax.swing.JButton resetjbutton;
    private javax.swing.JButton savejButton;
    private javax.swing.JButton searchjButton;
    private javax.swing.JTextField timejTextField8;
    private javax.swing.JButton updatejButton;
    private javax.swing.JTextField venuejTextField6;
    // End of variables declaration//GEN-END:variables

}
