/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * membership.java
 *
 * Created on Aug 3, 2017, 4:04:43 PM
 */

package collegeclub;
import java.sql.*;

/**
 *
 * @author HP
 */
public class membership extends javax.swing.JFrame {
    ConnectionClass cobj;
    PreparedStatement pst;
    ResultSet rst;
    long clbid[];
    long mid;
    /** Creates new form membership */
    public membership() {
        initComponents();
        cobj = new ConnectionClass();
        cobj.Connect();
        clbid = new long[100];
        int index=0;
        try
        {
        pst= cobj.con.prepareStatement("select clubid, clubname from tbclub");
        rst = pst.executeQuery();
               while (rst.next())
               {
               clbid[index]=rst.getLong(1);
               index++;
               cidjComboBox.addItem(rst.getString(2));
               }
        rst.close();

        }
        catch(Exception ex)
        {
        System.out.print("error in inpopulating clbid"+ex);
        }
        cobj.DisConnect();


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        yearjTextField5 = new javax.swing.JTextField();
        mnamejLabel3 = new javax.swing.JLabel();
        emailjTextField6 = new javax.swing.JTextField();
        coursejLabel5 = new javax.swing.JLabel();
        cidjLabel2 = new javax.swing.JLabel();
        rolljTextField3 = new javax.swing.JTextField();
        resetjButton4 = new javax.swing.JButton();
        pendingjTextField10 = new javax.swing.JTextField();
        regjTextField8 = new javax.swing.JTextField();
        paidjLabel10 = new javax.swing.JLabel();
        contactjTextField7 = new javax.swing.JTextField();
        mnamejTextField2 = new javax.swing.JTextField();
        searchjButton2 = new javax.swing.JButton();
        contactjLabel8 = new javax.swing.JLabel();
        emailjLabel7 = new javax.swing.JLabel();
        yearjlabel6 = new javax.swing.JLabel();
        savejButton1 = new javax.swing.JButton();
        regjLabel9 = new javax.swing.JLabel();
        rolljlabel4 = new javax.swing.JLabel();
        pendingjLabel11 = new javax.swing.JLabel();
        cidjComboBox = new javax.swing.JComboBox();
        updatejButton3 = new javax.swing.JButton();
        paidjTextField9 = new javax.swing.JTextField();
        coursejTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jInternalFrame1.setTitle("Membership");
        jInternalFrame1.setVisible(true);

        yearjTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearjTextField5ActionPerformed(evt);
            }
        });

        mnamejLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Users-Name-icon (1).png"))); // NOI18N
        mnamejLabel3.setText("Member name");

        coursejLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Science-Courses-icon.png"))); // NOI18N
        coursejLabel5.setText("Course name");

        cidjLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Cursor-icon (1).png"))); // NOI18N
        cidjLabel2.setText("Select Club");

        resetjButton4.setFont(new java.awt.Font("Tahoma", 1, 11));
        resetjButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/reset.png"))); // NOI18N
        resetjButton4.setText("Reset");
        resetjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetjButton4ActionPerformed(evt);
            }
        });

        paidjLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/money-icon.png"))); // NOI18N
        paidjLabel10.setText("Paid amount");

        searchjButton2.setFont(new java.awt.Font("Tahoma", 1, 11));
        searchjButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Search-icon.png"))); // NOI18N
        searchjButton2.setText("Search");
        searchjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjButton2ActionPerformed(evt);
            }
        });

        contactjLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Phone-icon.png"))); // NOI18N
        contactjLabel8.setText("Contact number");

        emailjLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Mail-icon.png"))); // NOI18N
        emailjLabel7.setText("Email");

        yearjlabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/my-numbers-icon.png"))); // NOI18N
        yearjlabel6.setText("Year/session");

        savejButton1.setFont(new java.awt.Font("Tahoma", 1, 11));
        savejButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Apps-File-Save-B-icon.png"))); // NOI18N
        savejButton1.setText("Save");
        savejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButton1ActionPerformed(evt);
            }
        });

        regjLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Calendar-icon.png"))); // NOI18N
        regjLabel9.setText("Registration date");

        rolljlabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/numbers-icon.png"))); // NOI18N
        rolljlabel4.setText("Roll number");

        pendingjLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/money-icon.png"))); // NOI18N
        pendingjLabel11.setText("Pending amount");

        updatejButton3.setFont(new java.awt.Font("Tahoma", 1, 11));
        updatejButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/update.png"))); // NOI18N
        updatejButton3.setText("Update");
        updatejButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButton3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jInternalFrame1Layout = new org.jdesktop.layout.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jInternalFrame1Layout.createSequentialGroup()
                        .add(24, 24, 24)
                        .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(mnamejLabel3)
                            .add(cidjLabel2)
                            .add(rolljlabel4)
                            .add(coursejLabel5)
                            .add(yearjlabel6)
                            .add(emailjLabel7)
                            .add(contactjLabel8)
                            .add(regjLabel9)
                            .add(paidjLabel10)
                            .add(pendingjLabel11))
                        .add(84, 84, 84)
                        .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(coursejTextField4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .add(regjTextField8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .add(contactjTextField7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .add(yearjTextField5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .add(emailjTextField6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .add(paidjTextField9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .add(pendingjTextField10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, cidjComboBox, 0, 172, Short.MAX_VALUE)
                            .add(rolljTextField3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .add(mnamejTextField2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                        .add(125, 125, 125))
                    .add(jInternalFrame1Layout.createSequentialGroup()
                        .add(savejButton1)
                        .add(28, 28, 28)
                        .add(searchjButton2)
                        .add(41, 41, 41)
                        .add(updatejButton3)
                        .add(28, 28, 28)
                        .add(resetjButton4)))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(cidjComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cidjLabel2))
                .add(18, 18, 18)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(mnamejLabel3)
                    .add(mnamejTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(rolljlabel4)
                    .add(rolljTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(coursejLabel5)
                    .add(coursejTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(yearjlabel6)
                    .add(yearjTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(emailjLabel7)
                    .add(emailjTextField6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(contactjLabel8)
                    .add(contactjTextField7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(regjLabel9)
                    .add(regjTextField8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(paidjLabel10)
                    .add(paidjTextField9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(pendingjLabel11)
                    .add(pendingjTextField10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 72, Short.MAX_VALUE)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(savejButton1)
                        .add(searchjButton2))
                    .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(updatejButton3)
                        .add(resetjButton4)))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButton1ActionPerformed
        // TODO add your handling code here:
        if(mnamejTextField2.getText().equals(""))
        {
            System.out.println("Enter Membername");
        }
 else{
            cobj.Connect();
            try
            {
                pst=cobj.con.prepareStatement("{call prcInsertMember(?,?,?,?,?,?,?,?,?,?)} ");
                        pst.setLong(1,clbid[cidjComboBox.getSelectedIndex()]);
                        pst.setString(2,mnamejTextField2.getText());
                        pst.setString(3,rolljTextField3.getText());
                        pst.setString(4,coursejTextField4.getText());
                        pst.setString(5,yearjTextField5.getText());
                        pst.setString(6, emailjTextField6.getText());
                        pst.setString(7, contactjTextField7.getText());
                        pst.setString(8,regjTextField8.getText());
                        pst.setString(9,paidjTextField9.getText());
                        pst.setString(10,pendingjTextField10.getText());

                      if(pst.execute()==false)
                      {
                          if(pst.getUpdateCount()>0)
                          {
                              System.out.print("Record saved");
                              cidjComboBox.setSelectedIndex(0);
                              mnamejTextField2.setText("");
                              rolljTextField3.setText("");
                              coursejTextField4.setText("");
                              yearjTextField5.setText("");
                              emailjTextField6.setText("");
                             contactjTextField7.setText("");
                             regjTextField8.setText("");
                             paidjTextField9.setText("");
                             pendingjTextField10.setText("");

                          }
 else
                          {
                              System.out.println("Record already exists");
 }
                }
            }
            catch(Exception ex)
            {
                System.out.println("error in insert"+ex);
            }
            cobj.DisConnect();
 }
    }//GEN-LAST:event_savejButton1ActionPerformed

    private void searchjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjButton2ActionPerformed
        
            cobj.Connect();
            try

            {
                pst=cobj.con.prepareStatement("Select * from tbmembership where member_name=?");
                pst.setString(1,mnamejTextField2.getText());
                rst=pst.executeQuery();
                if(rst.next())
                {
                    mid=rst.getLong(1);
                    cidjComboBox.setSelectedIndex(new searcharray().find(clbid,rst.getLong(2)));
                    mnamejTextField2.setText(rst.getString(3).trim());
                    rolljTextField3.setText(rst.getString(4).trim());
                    coursejTextField4.setText(rst.getString(5).trim());
                    yearjTextField5.setText(rst.getString(6).trim());
                    emailjTextField6.setText(rst.getString(7).trim());
                    contactjTextField7.setText(rst.getString(8).trim());
                    regjTextField8.setText(rst.getString(9).trim());
                    paidjTextField9.setText(rst.getString(10).trim());
                   pendingjTextField10.setText(rst.getString(11).trim());

                }
 
 else
                {
                    System.out.println("record not found");
                }
 }
                
            
        
 catch(Exception ex)
            {
     System.out.println("error in search"+ex);

            }
 cobj.DisConnect();


 
            
 
    }//GEN-LAST:event_searchjButton2ActionPerformed

    private void updatejButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButton3ActionPerformed
cobj.Connect();
try
{
    pst=cobj.con.prepareCall("{call prcUpdateMember(?,?,?,?,?,?,?,?,?,?,?)}");
pst.setLong(1,mid);
pst.setLong(2,clbid[cidjComboBox.getSelectedIndex()]);
pst.setString(3,mnamejTextField2.getText());
pst.setString(4,rolljTextField3.getText());
pst.setString(5,coursejTextField4.getText());
pst.setString(6,yearjTextField5.getText());
pst.setString(7,emailjTextField6.getText());
pst.setString(8,contactjTextField7.getText());
pst.setString(9,regjTextField8.getText());
pst.setString(10,paidjTextField9.getText());
pst.setString(11, pendingjTextField10.getText());
if(pst.execute()==false)
{
    if(pst.getUpdateCount()>0)
    {
        System.out.println("Record Updated");
        cidjComboBox.setSelectedIndex(0);
        mnamejTextField2.setText("");
        rolljTextField3.setText(""); 
        coursejTextField4.setText("");
        yearjTextField5.setText("");
        emailjTextField6.setText("");
        contactjTextField7.setText("");
        regjTextField8.setText("");
        paidjTextField9.setText("");
        pendingjTextField10.setText("");
    }
 else{
        System.out.println("Record not updated");
 }
}
        }
catch(Exception ex)
{
    System.out.println("Error in Update"+ex);
}
cobj.DisConnect();
    }//GEN-LAST:event_updatejButton3ActionPerformed

    private void yearjTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearjTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearjTextField5ActionPerformed

    private void resetjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetjButton4ActionPerformed
       cidjComboBox.setSelectedIndex(0);
        mnamejTextField2.setText("");
        rolljTextField3.setText("");
        coursejTextField4.setText("");
        yearjTextField5.setText("");
        emailjTextField6.setText("");
        contactjTextField7.setText("");
        regjTextField8.setText("");
        paidjTextField9.setText("");
        pendingjTextField10.setText("");
    }//GEN-LAST:event_resetjButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new membership().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cidjComboBox;
    private javax.swing.JLabel cidjLabel2;
    private javax.swing.JLabel contactjLabel8;
    private javax.swing.JTextField contactjTextField7;
    private javax.swing.JLabel coursejLabel5;
    private javax.swing.JTextField coursejTextField4;
    private javax.swing.JLabel emailjLabel7;
    private javax.swing.JTextField emailjTextField6;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel mnamejLabel3;
    private javax.swing.JTextField mnamejTextField2;
    private javax.swing.JLabel paidjLabel10;
    private javax.swing.JTextField paidjTextField9;
    private javax.swing.JLabel pendingjLabel11;
    private javax.swing.JTextField pendingjTextField10;
    private javax.swing.JLabel regjLabel9;
    private javax.swing.JTextField regjTextField8;
    private javax.swing.JButton resetjButton4;
    private javax.swing.JTextField rolljTextField3;
    private javax.swing.JLabel rolljlabel4;
    private javax.swing.JButton savejButton1;
    private javax.swing.JButton searchjButton2;
    private javax.swing.JButton updatejButton3;
    private javax.swing.JTextField yearjTextField5;
    private javax.swing.JLabel yearjlabel6;
    // End of variables declaration//GEN-END:variables

}