/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * participant.java
 *
 * Created on Aug 3, 2017, 3:02:15 PM
 */

package collegeclub;
import java.sql.*;
/**
 *
 * @author HP
 */
public class participant extends javax.swing.JFrame {
ConnectionClass cobj;
    PreparedStatement pst;
    ResultSet rst;
    long eid[];
    long pid;
    /** Creates new form participant */
    public participant() {
        initComponents();
        cobj = new ConnectionClass();
        cobj.Connect();
        eid = new long[100];
        int index=0;
        try
        {
        pst= cobj.con.prepareStatement("select eventid, name from tbevent");
        rst = pst.executeQuery();
               while (rst.next())
               {
               eid[index]=rst.getLong(1);
               index++;
               eventidjComboBox1.addItem(rst.getString(2).trim());
               }
        rst.close();

        }
        catch(Exception ex)
        {
        System.out.print("error in inpopulating clbid"+ex);
        }
        cobj.DisConnect();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        yearjLabel7 = new javax.swing.JLabel();
        eidjLabel2 = new javax.swing.JLabel();
        pendingjLabel12 = new javax.swing.JLabel();
        paidjLabel11 = new javax.swing.JLabel();
        resultjLabel13 = new javax.swing.JLabel();
        fnamejTextField3 = new javax.swing.JTextField();
        emailjLabel8 = new javax.swing.JLabel();
        fnamejLabel4 = new javax.swing.JLabel();
        paidjTextField10 = new javax.swing.JTextField();
        enrolljTextField9 = new javax.swing.JTextField();
        eventidjComboBox1 = new javax.swing.JComboBox();
        pendingjTextField11 = new javax.swing.JTextField();
        enrolldatejLabel10 = new javax.swing.JLabel();
        contactjLabel9 = new javax.swing.JLabel();
        namejTextField2 = new javax.swing.JTextField();
        emailjTextField7 = new javax.swing.JTextField();
        rolljLabel5 = new javax.swing.JLabel();
        searchjButton2 = new javax.swing.JButton();
        resetjButton4 = new javax.swing.JButton();
        yearjTextField6 = new javax.swing.JTextField();
        coursejTextField5 = new javax.swing.JTextField();
        rolljTextField4 = new javax.swing.JTextField();
        resultjTextField12 = new javax.swing.JTextField();
        updatejButton3 = new javax.swing.JButton();
        savejButton1 = new javax.swing.JButton();
        coursejLabel6 = new javax.swing.JLabel();
        namejLabel3 = new javax.swing.JLabel();
        contactjTextField8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setTitle("Participant");
        jInternalFrame1.setVisible(true);

        yearjLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/my-numbers-icon.png"))); // NOI18N
        yearjLabel7.setText("Year/Semester");

        eidjLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Cursor-icon (1).png"))); // NOI18N
        eidjLabel2.setText("Select Event");

        pendingjLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/money-icon.png"))); // NOI18N
        pendingjLabel12.setText("Pending amount");

        paidjLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/money-icon.png"))); // NOI18N
        paidjLabel11.setText("Paid amount");

        resultjLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Badge-Prize-icon.png"))); // NOI18N
        resultjLabel13.setText("Result");

        emailjLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Mail-icon.png"))); // NOI18N
        emailjLabel8.setText("Email");

        fnamejLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Office-Customer-Male-Light-icon.png"))); // NOI18N
        fnamejLabel4.setText("Father's name");

        enrolldatejLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Calendar-icon (1).png"))); // NOI18N
        enrolldatejLabel10.setText("Enrollment date");

        contactjLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Phone-icon.png"))); // NOI18N
        contactjLabel9.setText("Contact number");

        rolljLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/numbers-icon.png"))); // NOI18N
        rolljLabel5.setText("Roll number");

        searchjButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchjButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Search-icon.png"))); // NOI18N
        searchjButton2.setText("Search");
        searchjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjButton2ActionPerformed(evt);
            }
        });

        resetjButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        resetjButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/reset.png"))); // NOI18N
        resetjButton4.setText("Reset");
        resetjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetjButton4ActionPerformed(evt);
            }
        });

        updatejButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updatejButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/update.png"))); // NOI18N
        updatejButton3.setText("Update");
        updatejButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButton3ActionPerformed(evt);
            }
        });

        savejButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        savejButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Apps-File-Save-B-icon.png"))); // NOI18N
        savejButton1.setText("Save");
        savejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButton1ActionPerformed(evt);
            }
        });

        coursejLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Science-Courses-icon.png"))); // NOI18N
        coursejLabel6.setText("Course name");

        namejLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/collegeclub/resources/Users-Name-icon (1).png"))); // NOI18N
        namejLabel3.setText("Name");

        org.jdesktop.layout.GroupLayout jInternalFrame1Layout = new org.jdesktop.layout.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jInternalFrame1Layout.createSequentialGroup()
                        .add(savejButton1)
                        .add(18, 18, 18)
                        .add(searchjButton2))
                    .add(jInternalFrame1Layout.createSequentialGroup()
                        .add(21, 21, 21)
                        .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(eidjLabel2)
                            .add(namejLabel3)
                            .add(fnamejLabel4)
                            .add(rolljLabel5)
                            .add(coursejLabel6)
                            .add(yearjLabel7)
                            .add(emailjLabel8)
                            .add(contactjLabel9)
                            .add(enrolldatejLabel10)
                            .add(paidjLabel11)
                            .add(pendingjLabel12)
                            .add(resultjLabel13))))
                .add(18, 18, 18)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jInternalFrame1Layout.createSequentialGroup()
                        .add(updatejButton3)
                        .add(18, 18, 18)
                        .add(resetjButton4))
                    .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, pendingjTextField11)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, paidjTextField10)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, enrolljTextField9)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, contactjTextField8)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, emailjTextField7)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, yearjTextField6)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, coursejTextField5)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, rolljTextField4)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, fnamejTextField3)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, namejTextField2)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, resultjTextField12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, eventidjComboBox1, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(eidjLabel2)
                    .add(eventidjComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(namejLabel3)
                    .add(namejTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(fnamejLabel4)
                    .add(fnamejTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(rolljLabel5)
                    .add(rolljTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(coursejLabel6)
                    .add(coursejTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(yearjLabel7)
                    .add(yearjTextField6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(emailjLabel8)
                    .add(emailjTextField7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(contactjLabel9)
                    .add(contactjTextField8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(enrolldatejLabel10)
                    .add(enrolljTextField9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(paidjLabel11)
                    .add(paidjTextField10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(pendingjLabel12)
                    .add(pendingjTextField11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(resultjLabel13)
                    .add(resultjTextField12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 52, Short.MAX_VALUE)
                .add(jInternalFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(searchjButton2)
                    .add(updatejButton3)
                    .add(resetjButton4)
                    .add(savejButton1))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jInternalFrame1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButton1ActionPerformed
        if(namejTextField2.getText().equals(""))
        {
            System.out.print("Enter name");
        }
 else{
            cobj.Connect();
            try{
                pst=cobj.con.prepareStatement("{call prcInsertParticipant(?,?,?,?,?,?,?,?,?,?,?,?)} ");
                        pst.setLong(1,eid[eventidjComboBox1.getSelectedIndex()]);
                        pst.setString(2,namejTextField2.getText());
                        pst.setString(3,fnamejTextField3.getText());
                        pst.setString(4,rolljTextField4.getText());
                        pst.setString(5,coursejTextField5.getText());
                        pst.setString(6,yearjTextField6.getText());
                        pst.setString(7, emailjTextField7.getText());
                        pst.setString(8,contactjTextField8.getText());
                        pst.setString(9,enrolljTextField9.getText());
                        pst.setString(10,paidjTextField10.getText());
                        pst.setString(11,pendingjTextField11.getText());
                        pst.setString(12,resultjTextField12.getText());

                      if(pst.execute()==false)
                      {
                          if(pst.getUpdateCount()>0)
                          {
                              System.out.print("Record saved");
                              eventidjComboBox1.setSelectedIndex(0);
                              namejTextField2.setText("");
                              fnamejTextField3.setText("");
                              rolljTextField4.setText("");
                              coursejTextField5.setText("");
                              yearjTextField6.setText("");
                              emailjTextField7.setText("");
                             contactjTextField8.setText("");
                             enrolljTextField9.setText("");
                             paidjTextField10.setText("");
                             pendingjTextField11.setText("");
                             resultjTextField12.setText("");

                          }
 else
                          {
                              System.out.println("Record already exists");
 }

            }
            }
            catch(Exception ex)
            {
            System.out.println("Error in insert"+ex);
            }
 }
        cobj.DisConnect();

    }//GEN-LAST:event_savejButton1ActionPerformed

    private void searchjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjButton2ActionPerformed
         cobj.Connect();
            try

            {
                pst=cobj.con.prepareStatement("Select * from tbparticipant where name=?");
                pst.setString(1,namejTextField2.getText());
                rst=pst.executeQuery();
                if(rst.next())
                {
                    pid=rst.getLong(1);
                    eventidjComboBox1.setSelectedIndex(new searcharray().find(eid,rst.getLong(2)));
                    namejTextField2.setText(rst.getString(3).trim());
               fnamejTextField3.setText(rst.getString(4).trim());
                    rolljTextField4.setText(rst.getString(5).trim());
                    coursejTextField5.setText(rst.getString(6).trim());
                    yearjTextField6.setText(rst.getString(7).trim());
                    emailjTextField7.setText(rst.getString(8).trim());
                    contactjTextField8.setText(rst.getString(9).trim());
                    enrolljTextField9.setText(rst.getString(10).trim());
                    paidjTextField10.setText(rst.getString(11).trim());
                   pendingjTextField11.setText(rst.getString(12).trim());
                   resultjTextField12.setText(rst.getString(13).trim());

                }

 else
                {
                    System.out.println("record not found");
                }
 }



 catch(Exception ex)
            {
     System.out.println("error in search"+ex);

            }
 cobj.DisConnect();
    }//GEN-LAST:event_searchjButton2ActionPerformed

    private void updatejButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButton3ActionPerformed
    cobj.Connect();
     try{
         pst=cobj.con.prepareCall("{call prcUpdateParticipant(?,?,?,?,?,?,?,?,?,?,?,?,?)}");
        pst.setLong(1, pid);
                  pst.setLong(2,eid[eventidjComboBox1.getSelectedIndex()]);
                        pst.setString(3,namejTextField2.getText());
                        pst.setString(4,fnamejTextField3.getText());
                        pst.setString(5,rolljTextField4.getText());
                        pst.setString(6,coursejTextField5.getText());
                        pst.setString(7,yearjTextField6.getText());
                        pst.setString(8, emailjTextField7.getText());
                        pst.setString(9,contactjTextField8.getText());
                        pst.setString(10,enrolljTextField9.getText());
                        pst.setString(11,paidjTextField10.getText());
                        pst.setString(12,pendingjTextField11.getText());
                        pst.setString(13,resultjTextField12.getText());

                      if(pst.execute()==false)
                      {
                          if(pst.getUpdateCount()>0)
                          {
                              System.out.print("Record Updated");

                              eventidjComboBox1.setSelectedIndex(0);
                              namejTextField2.setText("");
                              fnamejTextField3.setText("");
                              rolljTextField4.setText("");
                              coursejTextField5.setText("");
                              yearjTextField6.setText("");
                              emailjTextField7.setText("");
                             contactjTextField8.setText("");
                             enrolljTextField9.setText("");
                             paidjTextField10.setText("");
                             pendingjTextField11.setText("");
                             resultjTextField12.setText("");

                          }
 else
                          {
                              System.out.println("Record not updated");
 }

            }
            }
            catch(Exception ex)
            {
            System.out.println("Error in update"+ex);
            }

    }//GEN-LAST:event_updatejButton3ActionPerformed

    private void resetjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetjButton4ActionPerformed
         eventidjComboBox1.setSelectedIndex(0);
                              namejTextField2.setText("");
                              fnamejTextField3.setText("");
                              rolljTextField4.setText("");
                              coursejTextField5.setText("");
                              yearjTextField6.setText("");
                              emailjTextField7.setText("");
                             contactjTextField8.setText("");
                             enrolljTextField9.setText("");
                             paidjTextField10.setText("");
                             pendingjTextField11.setText("");
                             resultjTextField12.setText("");
    }//GEN-LAST:event_resetjButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new participant().setVisible(true);
            }
        });

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contactjLabel9;
    private javax.swing.JTextField contactjTextField8;
    private javax.swing.JLabel coursejLabel6;
    private javax.swing.JTextField coursejTextField5;
    private javax.swing.JLabel eidjLabel2;
    private javax.swing.JLabel emailjLabel8;
    private javax.swing.JTextField emailjTextField7;
    private javax.swing.JLabel enrolldatejLabel10;
    private javax.swing.JTextField enrolljTextField9;
    private javax.swing.JComboBox eventidjComboBox1;
    private javax.swing.JLabel fnamejLabel4;
    private javax.swing.JTextField fnamejTextField3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel namejLabel3;
    private javax.swing.JTextField namejTextField2;
    private javax.swing.JLabel paidjLabel11;
    private javax.swing.JTextField paidjTextField10;
    private javax.swing.JLabel pendingjLabel12;
    private javax.swing.JTextField pendingjTextField11;
    private javax.swing.JButton resetjButton4;
    private javax.swing.JLabel resultjLabel13;
    private javax.swing.JTextField resultjTextField12;
    private javax.swing.JLabel rolljLabel5;
    private javax.swing.JTextField rolljTextField4;
    private javax.swing.JButton savejButton1;
    private javax.swing.JButton searchjButton2;
    private javax.swing.JButton updatejButton3;
    private javax.swing.JLabel yearjLabel7;
    private javax.swing.JTextField yearjTextField6;
    // End of variables declaration//GEN-END:variables

}
